default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
        exclude: ^test/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.7"
    hooks:
      - id: ruff
        name: "ruff"
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
        name: "ruff format"

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
